
  - description: null
    label: "Globals"
    name: "clippings"
    sort: 1
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/clippings.yaml"
    fields:
      - name: "site_name"
        label: "Site Name"
        description: null
        datatype: "text"
        sort: 1
        required: false
        relationship: null
        settings:
          list: false
          options: {}
      - name: "logo"
        label: "Site Logo"
        description: null
        datatype: "images"
        sort: 2
        required: null
        relationship: null
        settings:
          limit: 1
          options: {}
      - name: "learn_more"
        label: "Learn More"
        description: "This link redirects to register page"
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "footer_title"
        label: "Footer Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: null
    label: "Homepage"
    name: "homepage"
    sort: 1
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/homepage.tpl"
    content: "/content/homepage.yaml"
    fields:
      - name: "image"
        label: "image"
        description: ""
        datatype: "images"
        sort: 10000
        required: true
        relationship: null
        settings:
          group_id: "1-e8d36d2-px2blz"
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Biography"
    name: "biography"
    sort: 100
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/biography.tpl"
    content: "/content/biography.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 0
        required: true
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "Description"
        description: "First paragraph description "
        datatype: "wysiwyg_basic"
        sort: 1
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Navigation"
    name: "navigation"
    sort: 106
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    content: "/content/navigation.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "page_link"
        label: "Page Link"
        description: "Select existing content item that this navigation item will route to."
        datatype: "internal_link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "external_page"
        label: "External page"
        description: "If internal link is blank then external link will be used."
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "sort_by"
        label: "Sort"
        description: ""
        datatype: "sort"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Career"
    name: "career"
    sort: 117
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/career.tpl"
    content: "/content/career.yaml"
    fields: []
  - description: ""
    label: "Careers"
    name: "careers"
    sort: 119
    listed: true
    hasRoute: true
    showAsTable: true
    parent: "career"
    view: "/views/careers.tpl"
    content: "/content/careers.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "image"
        label: "Image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          group_id: "1-e8d36d2-px2blz"
          limit: "1"
          list: true
      - name: "sort_by"
        label: "Sort by"
        description: ""
        datatype: "sort"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Contact Us"
    name: "registration"
    sort: 121
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/registration.tpl"
    content: "/content/registration.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "description"
        label: "Description"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "form_title"
        label: "Form Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "label_input_1"
        label: "Label Input 1"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "label_input_2"
        label: "Label Input 2"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "label_input_3"
        label: "Label Input 3"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "submit_message"
        label: "Submit Message"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "message_placeholder"
        label: "Message placeholder"
        description: ""
        datatype: "textarea"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Footer"
    name: "footer"
    sort: 134
    listed: true
    hasRoute: false
    showAsTable: false
    parent: null
    view: "/views/footer.tpl"
    content: "/content/footer.yaml"
    fields:
      - name: "title"
        label: "Title"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "footer_icon"
        label: "Footer Icon"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "sort_by"
        label: "Sort by"
        description: ""
        datatype: "sort"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "footer_url"
        label: "Footer Url"
        description: ""
        datatype: "link"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
